### ISSUE TITLE
3/3 Filters

### ISSUE THREAD

**Issue by be-novelt** [WorldHealthOrganization/herams-backend#107]
3/3 > Filters screens seen today w/ @SamuelPetragallo 

![HeRAMs_filters1](https://user-images.githubusercontent.com/43411015/55975018-4f2af100-5c89-11e9-990f-ed4b8506fcaa.jpg)
![HeRAMs_filters2](https://user-images.githubusercontent.com/43411015/55975019-4fc38780-5c89-11e9-9b0e-09f0a8f609db.jpg)

**Comment by SamMousa** [comment]
Partially implemented

**Comment by SamMousa** [comment]
@jeremiehelme what do you think of these mock ups? 
We should choose whether we want to use them, if not we can close this issue.

**Comment by jeremiehelme** [comment]
@SamMousa This is the mockup I used to style the filters
I would need help for to things 
- to add the number of filters selected inside the button and at the bottom of the list
- to show checkboxes instead of input, if it is important / possible ?

For the buttons "Clear" and "Apply", I would need you to merge some PR first, so I can add the correct class to them 
- [Cleaning css](https://github.com/WorldHealthOrganization/herams-backend/pull/319)
- [button styles](https://github.com/WorldHealthOrganization/herams-backend/pull/350)

**Comment by jeremiehelme** [comment]
Thanks !

I Updated the style and buttons according to the mockup
(Had to change the default buttons style a bit too)

<img width="1440" alt="Capture d’écran 2020-02-27 à 16 02 15" src="https://user-images.githubusercontent.com/2345926/75456391-bffafa80-597a-11ea-8cbc-e24ae1050a04.png">

<img width="1440" alt="Capture d’écran 2020-02-27 à 16 02 27" src="https://user-images.githubusercontent.com/2345926/75456408-c4271800-597a-11ea-8305-88a3b392ddfc.png">
