### ISSUE TITLE
User stories

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#114]
[HeRAMS_User_Stories_20190415.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3079243/HeRAMS_User_Stories_20190415.docx)

**Comment by SamMousa** [comment]
For easier reference: 

## User stories
### 1 Platform admin: manages more than one project, creates new projects, assigns “Project admin” role. Typically connects and

a. Creates a new project, links it to an existing ls survey (+ does all the necessary setup in ls), customizes the project pages (dashboard) and map/charts as needed
b. Manages existing projects: accesses/manages users that have access to a given project
c. Manages the settings of various projects (former “Tool” page (https://primewho.org/tools)  

### 2 Project admin: in charge of managing access to and users of a given project. Typically connects and

a. Goes directly (and only) to a given project
b. Creates/manages WSs (implies working in ls too  ls access)
c. Accesses all WSs of that project
d. Manages users of that project (allows access requests to the project, etc.)
e. Possibly (in the future) customizes the dashboards

### 3 WS owner: manages generally one (occasionally several) WSs. Typically connects and

a. Goes to a given project/WSs
b. Consumes data from the dashboards/exports reports, etc
c. Shares access to those WSs with other users and generally manages access to the WSs he/she is in charge of

### 4 Data contributor: doesn't own a WS but has been granted access to contribute data to the process. Typically connects and

a. Goes directly to a given project/WS
b. Consumes data from the dashboards/exports reports, etc
c. Goes to his/her WS (typically 1 per contributor) and works on data (data edit function linking him/her to the response table and various edit/update functions)

### 5 Data viewer: is granted access to WS(s) (read only mode)

a. Goes directly to a given project/WS
b. Consumes data from the dashboards/exports reports, data, etc
c. Views detailed data from the WS(s) he/she has been granted access to

### 6 Data consumer

a. Goes directly to a given project
b. Consumes data from the dashboards/exports reports, etc
c. Doesn’t have access to WSs (but may go to the list of WSs and request extended permissions to become Data viewer, contributor, etc.)

**Comment by SamMousa** [comment]
| Subject  | Permission | Stories
| ------------- | ------------- | ------------- |
| Global          | Admin | 1 |
| Project         | Read   | 6a, 6b, 6c, 5a, 5b, 4a, 4b, 3a, 3b, 2a,  |
| Project         | Write   | 2b, 2c |
| Project         | Admin | 2d, 2e |
| Workspace  | Write   | 4c  |
| Workspace  | Admin | 3c  |

Because of 2d, every user can access the list of projects in the system.
Because of 6c, every user can access the list of workspaces for each project in the system.


Currently we have a simple navigation structure:
```
World map
├── Project popup
    └── Project dashboard main page
        └── Project dashboard secondary page(s)
└── Admin dashboard
    ├── Project list
         ├── Update
             └── Create / edit dashboard page
                 └── Create edit element
         ├── Share
         ├── Request access
         └── Workspace list
             ├── Update
             ├── Share
             └── Request access
    ├── User management
    └── Limesurvey SSO
                  

```

Separating data consumption from administrative tasks means that switching between the two is not very efficient when counting clicks. It is however very easy to grasp.
Because of user stories `2d` en `6c` the project list and workspace list are needed for every user; this means that any navigational shortcuts will not replace the tree, but change it into a directed graph.
For most people a simple structure, even if not the most efficient, is easier to grasp than a complexer but theoretically more efficient method.

Other advantages of the current tree include:
- It is consistent even when a users' permissions change.
- Admins, who are most likely first support contact as well, have the same tree as users, making support easier.

While I do like adding shortcuts to places that have a one to one mapping, for example jumping directly to the element editor:
![image](https://user-images.githubusercontent.com/547021/56121674-ee453680-5f70-11e9-9a92-a183eda4edd0.png)

Doing this in places where the mapping is not one to one is conceptually harder to understand.

Instead of trying to optimize this for different users I propose leaving the existing navigation unchanged, except for one thing.

Currently the admin dashboard is empty. When we implement the dashboard we can add several shortcuts here to help the user without taking away the consistent navigation.
Examples could include:
- A card for recently accesed projects or workspaces.
- A card for managing a workspace if there are only < X workspaces a user can access.
- An information card explaining users they can use their browsers' bookmark to efficiently navigate to pages they often need.
- Allowing users to star pages which in turn will create a card on the admin dashboard for easier navigation.

All of these aids do not change the core concept of 2 environments: data consumption and contribution. When switching to the admin page we have consistent navigation which can then be tailored to a user after they have learned to use the navigation menus.
