### ISSUE TITLE
Editing support for the graph of HeRAMS PHL 

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#162]
How can I edit the total number of health facilities for the Philippines dashboard from 6207 to 28996 as well as the number per health facility type to a total of 28996?

<img width="1680" alt="Screen Shot 2019-07-10 at 6 07 37 PM" src="https://user-images.githubusercontent.com/50957748/60961170-1ceb6700-a33e-11e9-9ca0-e574eb723b90.png">

**Comment by SamMousa** [comment]
The total number of HFs in a project can be overridden at the project level.
You cannot override individual data points, for that you will need to enable the workspaces and so the actual data is imported.

Also note that in the project dashboard the real result is always shown and not the overridden value, since that would be confusing with respect to filtering and analysis.

**Comment by JeffDotingco** [comment]
I just did that by enabling all the workspaces. :) The problem now is that I slowed down the platform again. Apologies. I will never enable all the WS again until a stable platform is up and running.
