### ISSUE TITLE
HeRAMS Cox's Bazar initial dataset configuration to the platform

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#163]
The 374 workspaces for HeRAMS Cox's Bazar are shown as tokens and not as attributes (HF_code and Health_Facility_Name). Need some help how to change them into HF_code and Health facility name. Thanks! :)
<img width="1680" alt="Screen Shot 2019-07-15 at 10 20 29 PM" src="https://user-images.githubusercontent.com/50957748/61223384-1baba700-a74f-11e9-916c-71bb576f7d09.png">

**Comment by SamMousa** [comment]
When importing the workspaces you choose which field from the token to use as a workspace title.
If it imported the token, you chose the token field, so it shows token.

If you want to use a different field, you will have to delete the workspaces and reimport them. 
Alternatively you may manually correct them.

Please document this as well, since apparently this screen:
![image](https://user-images.githubusercontent.com/547021/61275917-3d3c7b00-a7af-11e9-8455-786c97ca2d5b.png)

is not clear enough.

Have you read it, or did you just click import too fast?

**Comment by JeffDotingco** [comment]
Thanks Sam! I just imported the WS the fast way. ;)

**Comment by SamMousa** [comment]
That's not true, the fast way is to know what you're doing; this blindly clicking next means you don't know what you're doing.
Check what you are doing carefully, if you are not sure, ask questions or consult documentation *before* you continue.

**Comment by JeffDotingco** [comment]
Okay Sam. Noted with thanks.
