### ISSUE TITLE
Feedbacks for the HeRAMS approach e-learning module of the GHC

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#173]
Feedbacks for HeRAMS Approach e-learning module that can be accessed at https://filer.indecommlearning.com/clients/WHO/WHO07/M13_The_HeRAMS_Approach/story_html5.html?lms=1

**Comment by JeffDotingco** [comment]
1. HeRAMS Core principles should be updated (location: page 7/19) including updating the Core principle question in the assessment (location: page 18/19)
2. Based on the latest SOP, we added Pre-assessment as the first step in the inc-country implementation. "Dismantling reports" is also in the monitoring steps, that should be "disseminating reports" (location: page 10/19)
3. Question 5/10 should be changed to "Which of these information pillars of HeRAMS assesses the main causes for the lack of functionality?" (location: page 18/19)
4. The activity option "Dismantling reports" in Question 11/10 should be rephrased to "Report and disseminate"

**Comment by luna404** [comment]
Adding to Jeff's list

1.  Slides 1 & 7: The maps show Sudan w/o South Sudan. In the latter case I don't think this is appropriate. For the map on the first slide this is appropriate for 2007, but when other countries are being added where HeRMAS was conducted more recently it becomes a little confusing. Maybe we could display the countries as dots instead? I would also recommend changing zoom level. It is very focused on Africa and does not show the Philippines and Fiji. Also, OPT is not mentioned here but their dashboard is displayed on slide 13.
2.  Slide 4: There is a pronunciation error. The speaker says “Cluster Led Agency” instead of “Cluster Lead Agency”.
3.  Slide 14: Should be rephrased to “HeRAMS contributes to an efficient WHO and health sector response”, rather than “HeRAMS has an efficient WHO and health sector response”,
4.  Slide 18: It states there are 10 questions, but there are 15 questions. Moreover, question 11 – 15 are labelled as X out of 10. 
5.  Slide 18 Q1: Should the question be when or where is HeRAMS used?

**Comment by luna404** [comment]
1. On slide 8, the speak is talking over himself when you click on the squares to early.
2.  Jeff and I both think that some of the test questions are a little tricky. I just had a quick chat with Emma from the HC and she mentioned that it's very important that the questions are straight forward. Could we spend some time in the meeting tomorrow to brainstorm how to make them easier for participants?

**Comment by SamuelPetragallo** [comment]
> 1. HeRAMS Core principles should be updated (location: page 7/19) including updating the Core principle question in the assessment (location: page 18/19)
> 2. Based on the latest SOP, we added Pre-assessment as the first step in the in-country implementation. "Dismantling reports" is also in the monitoring steps, that should be "disseminating reports" (location: page 10/19)
> 3. Question 5/10 should be changed to "Which of these information pillars of HeRAMS assesses the main causes for the lack of functionality?" (location: page 18/19)
> 4. The activity option "Dismantling reports" in Question 11/10 should be rephrased to "Disseminating reports"

Ok Jeff for points 1. to 4. - can you please implement in the shared doc?

**Comment by SamuelPetragallo** [comment]
Folks - went through your comments now and agree on all. Would add that:
- the pronounciation of "HéRAMS" is a little weird
- pictures are mostly irrelevant 
- map is irrelevant

Could you prepare a set of screenshots and pictures to be used instead (not sure what the first one is about - looks like bored people waiting to start a boring meeting).

I think the global dashboard map solves the map issue. Then @JeffDotingco do you have any field/training pictures that are more relevant? could you please prepare a folder and name these picture with the slide number we recommend them for?

Once ready I'll pass that back to GHC, thanks both for the torough review!

**Comment by JeffDotingco** [comment]
Okay @SamuelPetragallo, I have Yemen and Pakistan TOT pictures

**Comment by JeffDotingco** [comment]
I have already created a folder (HERAMS Pictures for GHC) in the google shared drive. A word file is included with a table showing the picture that needs to be replaced with another picture. @SamuelPetragallo, there are notes in the file stating that HeRAMS platform pictures will come from your platform account screenshot. Please add pictures that need to be replaced if you have some pictures relevant to HeRAMS or health service delivery.

**Comment by FatmaGiha** [comment]
Colleagues, I totally agree with all your comments, and add:
- slide 17 - Summary: if we can lessen the time that word "HeRAMS" appears and said, would be better. the “HeRAMS” pronunciation is weird, and having it that frequent sounds more weird :)
Nothing more to add from my side, please feel free to pass it to the GHC team...
