### ISSUE TITLE
"Causes of Unavailability" graph in HeRAMS NGA is not shown

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#180]
Causes of Unavailability chart in HeRAMS NGA is not shown in the overview (id: 179; sort number: 5) and service availability (id: 35; sort number: 2) probably affected by the size of the graph legend.

<img width="1680" alt="Screen Shot 2019-08-19 at 11 03 08 PM" src="https://user-images.githubusercontent.com/50957748/63276571-320ccb80-c2d6-11e9-9e02-bc755ed3232f.png">

**Comment by SamMousa** [comment]
We could put the legend in the bottom of the graph; but regardless of what we choose, at some point there is too much text to effectively fit in the box.
An alternative would be to allow different sizes (2x1, 1x2 or 2x2) for the chart.
@SamuelPetragallo what do you think?
![image](https://user-images.githubusercontent.com/547021/63426554-6b972100-c413-11e9-9b01-92c7fef38da3.png)

**Comment by luna404** [comment]
I like the ideas of putting the legend on bottom (or top) and having different sizes available. We would still have the issue that the chart sizes vary depending on the size of the legend. I would prefer if all charts are the same size and we change the legend size instead. If you look at other dashboard software, they usually crop the legend rather than reducing the chart size. 

Here's an example how PowerBI addresses the issue. It crops the legend text but you can still get the entire text string on mouse-over.

![image](https://user-images.githubusercontent.com/18245059/63434821-19133000-c426-11e9-8a2f-7742e8c9cf9e.png)

For the maps, I think it would be better if the legend is hidden by default. Depending on the country's shape, the legend will overlap with the data (see the second map in your example). Also it would be great if we could have different size for maps. Not all countries fit into the 2x1 format. If you look at the example of Nigeria above, we "waste" a lot of the map on other countries.

**Comment by SamMousa** [comment]
You can always zoom out further in case you want to see the whole country and the legend is overlapping; we can probably do that intelligently.

Sizing is a think we could make configurable. (Note that the map is currently 2 x 2, measured in blocks).

I'm not a fan of making the visible information only available on hover (it makes it impossible to get decent PDFs for example). Added here #192
