### ISSUE TITLE
HeRAMS NGA service availability table on main problem per state / LGA needs to be changed to lack of staff etc instead of A1, A2, A3, A4

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#197]
HeRAMS NGA service availability table (id: 36) on main problem per state / LGA needs to be changed to the responses (e.g. Lack of health staff) instead of A1, A2, A3, A4.

<img width="1680" alt="Screen Shot 2019-08-28 at 11 10 05 PM 2" src="https://user-images.githubusercontent.com/50957748/63868478-2a8da680-c9e9-11e9-8bb3-4cf471b3a8dc.png">

**Comment by SamMousa** [comment]
Is this is specific for that table?

**Comment by JeffDotingco** [comment]
Yes. Other tables like this case already have the responses and not A1, A2, A3, A4 (e.g. reasons for nonaccessibility, non functionality)

**Comment by SamMousa** [comment]
@JeffDotingco this issue has been fixed.
Next time try to think with me instead of dumping all information:
- This issue was not related to Nigeria
- This issue was not related to service availability

The correct title would have been: Tables that use `transpose` and `Causes of unavailability` as reason display answer codes instead of texts in the `Main problem` column.
