### ISSUE TITLE
Display chart/map title in page update table

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#213]
Would it be possible to add the element title to the table listing all elements of a dashboard page (similar to the table displaying all available pages of a project)? At the moment it is difficult to know which element to edit and it involves a lot of back and worth to figure out the element id first. 

![image](https://user-images.githubusercontent.com/18245059/64539188-50d31080-d31e-11e9-907c-6ecb500545ff.png)

**Comment by luna404** [comment]
This is great. Minor comment on the title. As we are trying to always use the question text as header, this field will stay empty most of the time and therefore provides little added value. Could we instead display the question code with the text as done in the Code drop-down list and remove the title field?

**Comment by SamMousa** [comment]
No, that will make it a lot slower. We store the question code, which is why it is easy to show for many records.
Even if the title is not often used I see no advantage in removing it; this page is only used by people who have received training so they should be able to use whichever column is relevant for them. 
(By the same logic you would next suggest removing the id column)
