### ISSUE TITLE
Dashboard element height

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#218]
On bigger screens, the width of elements adjusts to the screen size but not the height. This results in half the page being empty . Could the element height also be responsive to the screen size? I would propose to limit the number of rows to 3. 

![image](https://user-images.githubusercontent.com/18245059/64619301-28144f00-d3e2-11e9-958a-e2701747c82b.png)

**Comment by luna404** [comment]
It's much better now. Thanks!

In the example below, the last row has a different height than the first two rows. Could this be changed to assure all rows have the same height?

![image](https://user-images.githubusercontent.com/18245059/65240417-88da1080-dae1-11e9-8282-39a2ee5b8777.png)

**Comment by SamMousa** [comment]
Not in a good way, the browser tries to pick a size between `200px` and `33%` for each row.
This way the system remains dynamic. Equal size is in my opinion not the most important thing, what we could increase is the minimum size though.

Also note that many people will not see what you see due to your screen size.
