### ISSUE TITLE
Push deletion of data from LS to HeRAMS

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#244]
HeRAMS is currently not notified when an entry is deleted.

Related to #239

**Comment by SamMousa** [comment]
@luna404 what is the use case for deleting HFs from LimeSurvey?
It seems to me that this is only relevant when testing, right?

**Comment by luna404** [comment]
The most common use case that requires deleting records is users creating duplicates. This is particularly an issue in countries using health districts which are usually based on catchment areas and therefore change frequently. This easily results in duplicates created by users as they don't know that the facility was entered under a different location name. During the data cleaning process, it must therefore be possible to delete these records.

**Comment by SamMousa** [comment]
Okay, so it's part of the "admin" flow, clear.

**Comment by SamMousa** [comment]
Please confirm that data is now always synchronized between Staging and platform.

- [ ] Removing a record via the response picker works
- [ ] Removing a single record via LS works
- [ ] Updating a record via the response picker works
- [ ] Creating a new record via the response picker

**Comment by SamuelPetragallo** [comment]
We discussed that briefly now - challenge in keeping this aligned is probably due to some of the back and forth on around data, such as creating, populating and then deleting WSs, etc.

I guess a lot of that will be solved once we manage HFs in HeRAMS only. In would be easier for us if we knew how the synch behaves. what it checks for, when, when data is updated or not (if that's not too much of a mess).

I think we also previously had an indication of when a given WS had last been synched which helps ruling synch out while testing - not sure if it can be useful to have that back.

**Comment by luna404** [comment]
Deleting is working, for other issues related to the data cache see issue #357

**Comment by JeffDotingco** [comment]
working in PROD: 59 records in a workspace created just for testing in LS (Test HeRAMS Yemen), deleted 8 records and this is reflected in the platform
