### ISSUE TITLE
Workspace and project level roles and some related issues in STAGING

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#256]
| Roles | Permissions and Restrictions  | Working / Not working in STAGING | Remarks
|--------|----------| --------- | ------- |
|Workspace contributor |PERMISSION 1: Can edit data in the WS | Working  | View, Edit, Delete, Register a New HF
| |PERMISSION 2: Can download data in the WS | **Not working**  | Error Message: PHP Notice – yii\base\ErrorException
| |PERMISSION 3: Can only view project dashboard | Working | 
| |RESTRICTION 1: Cannot share WS to others | Working | 
|Workspace owner |PERMISSION 1: Can edit data in the WS | Working  | View, Edit, Delete, Register a New HF
| |PERMISSION 2: Can download data in the WS | **Not working**  | Error Message: PHP Notice – yii\base\ErrorException
| |PERMISSION 3: Can share WS to others | **Not working**  | No sharing icon in the actions pane
| |PERMISSION 4: Can only view project dashboard | Working | 
|Project viewer |PERMISSION 1: Can view WSs | Working  | 
| |PERMISSION 2: Can only view project dashboard | Working  | 
| |RESTRICTION 1: Cannot edit data | Working  | 
| |RESTRICTION 2: Cannot download data in the WS | Working  | 
|Project owner |PERMISSION 1: Can view WSs |  | 
| |PERMISSION 2: Can only view project dashboard |  | 
| |PERMISSION 3: Can share project  |  | Same permissions as project viewer if project owners can't share project (project owner or admin access rights)
| |RESTRICTION 1: Cannot edit data |  | 
| |RESTRICTION 2: Cannot download data in the WS |  | 
|Project admin |PERMISSION 1: Can edit data in every WS | Working | View, Edit, Delete, Register a New HF
| |PERMISSION 2: Can download data in every WS | **Not working** | Error Message: PHP Notice – yii\base\ErrorException
| |PERMISSION 3: Can share WS to others | **Not working** | 
| |PERMISSION 4: Can download project-level data | **Not working** | Error if you go to backend administration, No download button in the actions pane
| |PERMISSION 5: Can create and import WS | Working | Import WS: Needs further testing 
| |PERMISSION 6: Can delete WS | Working  | 
| |PERMISSION 7: Can edit project settings (edit token) | Working  | Can only edit token title
| |PERMISSION 8: Can view, edit and delete project dashboard elements and pages | **Not working**  | Can only view dashboard through dashboard icon & world overview
| |PERMISSION 9: Can share project to Project owner and Project viewer | **Not working**  | 
| |RESTRICTION 1: Cannot share project to others for “project admin” rights | Working  | 
| |RESTRICTION 2: Cannot create/delete projects | Working | Needs further testing
|Global admin |PERMISSION 1: Can edit data in every WS | Working  | View, Edit, Delete, Register a New HF
| |PERMISSION 2: Can download data in every WS | **Not working**  | Error Message: PHP Notice – yii\base\ErrorException
| |PERMISSION 3: Can share workspaces | Working  | 
| |PERMISSION 4: Can download project-level data | **Not working**  | Error if you go to backend administration, No download button in the actions pane
| |PERMISSION 5: Can create WS | Working | Import WS: Needs further testing 
| |PERMISSION 6: Can delete WS | Working  | 
| |PERMISSION 7: Can share project to others (Project admin, owner, and viewer) | Working  | Working according to the current access rights (e.g. allow everything)
| |PERMISSION 8: Can edit settings | Working  | Can only edit token title
| |PERMISSION 9: Can view, create, edit and delete project dashboard elements and pages | Working  | 
| |PERMISSION 10: Can create and delete projects | **Not working**  | Needs further testing

**Comment by SamMousa** [comment]
I have added a lot of new permissions, but not the roles yet.
Here's a list of things you need to assign for each role.

**Workspace Contributor**
![image](https://user-images.githubusercontent.com/547021/72601252-54525600-3915-11ea-81e5-bef396a28e19.png)
Note that a user that has **any** permission on a workspace will be able to see the project dashboard.

**Workspace Owner**
![image](https://user-images.githubusercontent.com/547021/72601301-6af8ad00-3915-11ea-84dc-b8846bdf3396.png)
Note that a user that has **any** permission on a workspace will be able to see the project dashboard.

**Project Viewer**
![image](https://user-images.githubusercontent.com/547021/72601345-7f3caa00-3915-11ea-9dd1-7272dce72947.png)

**Project Owner**
![image](https://user-images.githubusercontent.com/547021/72601479-c6c33600-3915-11ea-87c2-5a391507be6f.png)

Note that the `can view WSs` permission is not relevant, there is no viewing a single workspace and viewing the list is open for everyone.

**Project Admin**
![image](https://user-images.githubusercontent.com/547021/72601580-f70ad480-3915-11ea-8fc8-85864ddd96dc.png)

**Comment by SamuelPetragallo** [comment]
@SamMousa have you been able to automate the testing of some (all?) of these rules yet?

**Comment by SamMousa** [comment]
Some, not all.

**Comment by luna404** [comment]
I noticed that when you share permission with a user it no longer shows the email, but only the name. Personally I would prefer if we could keep the email there. Names alone are not always unique and I like to have the email to lookup users.

**Comment by JeffDotingco** [comment]
I am testing through HeRAMS Pakistan as error occurs when you want to share Cox's Bazar and Philippines at the project level. The delete user icon is already not in the options

**Comment by luna404** [comment]
Workspace Owner is not able to share project with others. 

I granted the equivalent of workspace owner rights to the HeRAMS test user. But with the test user account I cannot share the worksapce further. 
I have access to the share page and I can share it with other users but they are not added.

Example: https://herams-staging.org/workspace/5402/share

**Comment by luna404** [comment]
Jeff and I tried to test all the individual permissions on both WS and project level.

1. Only Global administrators seem to be able to share (both on project and on workspace level). I.e. I can share but Jeff cannot and any other account I grant sharing privileges is also not able to share further. 
2. On a project level, it is not possible to share: 
  a. access to only the dashboard
  b. write access
  d. download. The icon is added but when you try to download the data you get an error that you're not allowed to perform this action
 
The rest seems to be functioning but we need more testing once the sharing issue is resolved.

**Comment by SamuelPetragallo** [comment]
FYI @SamMousa the testing of permissions can only resume once #276 is fixed

**Comment by JeffDotingco** [comment]
Testing of role permissions in staging 
(Individual-level permissions independent of roles also tested including "allow everything")

|Role |Permission|Permission Access|Status |Remarks|
|--------|----------| --------- | ------- | ------- |
|Workspace Contributor|Manage data in LimeSurvey|Can access dashboard through icon|Working
|||Can edit responses in WSs|Working
||Export, allows exporting data|Can download data per WS|Working |Data should follow LS format and include Response ID
|Workspace Owner|Manage data in LimeSurvey|Can access dashboard through icon|Working
|||Can edit responses in WSs|Working
||Export, allows exporting data|Can download data per WS|Working |Data should follow LS format and include Response ID
||**Share, allows this users to give other users limited access**|**Can share WS to others** |**Not working**
|Project Viewer|Read, this grants access to the dashboard|Can access dashboard through icon|Working
|||Can only see the WSs|Working
|Project Owner|Read, this grants access to the dashboard|Can access dashboard through icon|Working
||**Share, allows this users to give other users limited access**|**Share project to other users**|**Not working**|User name not appearing after being shared, "Permissions cannot be blank" notification appearing
|||**Share WS to other users** |**Not working**|User name not appearing after being shared, "Permissions cannot be blank" notification appearing
|Project Admin|Read, this grants access to the dashboard|Can access dashboard through icon|Working
|||Can only see the WSs|Working
||Manage data in LimeSurvey|Can edit responses in WSs|Working
||**Share, allows this users to give other users limited access**|**Share project to other users**|**Not working**|User name not appearing after being shared, "Permissions cannot be blank" notification appearing
|||**Share WS to other users** |**Not working**|User name not appearing after being shared, "Permissions cannot be blank" notification appearing
||Manage workspaces in the project|Can create, import, delete WS|Working
||**Share, allows this users to give other users limited access**|**Share project to other users**|**Not working**|User name not appearing after being shared, "Permissions cannot be blank" notification appearing
|||**Share WS to other users** |**Not working**|User name not appearing after being shared, "Permissions cannot be blank" notification appearing
||Read, this grants access to the dashboard|Can access dashboard through icon|Working
||**Share, allows this users to give other users limited access**|**Share project to other users**|**Not working**|User name not appearing after being shared, "Permissions cannot be blank" notification appearing
|||**Share WS to other users** |**Not working**|User name not appearing after being shared, "Permissions cannot be blank" notification appearing
||Manage workspaces in the project|Can delete, create, import WS|Working
||**Export, allows exporting data** |**Download project-level data (through the download icon at the project level)**|**Not working**| "You are not allowed to perform this action" notification appearing
|||Download WS-level data |Working|Data should follow LS format and include Response ID

**Comment by SamMousa** [comment]
You can't share with yourself, or did no username appear when you tried sharing?

**Comment by SamMousa** [comment]
Also WS owner should be able to share WS to others

**Comment by JeffDotingco** [comment]
@SamMousa I can't share a project and WS to myself. But now and I can share the WS and Project to others. If someone is a Project Owner (Quetta Division), the account couldn't share the project to others (Kalat Division) as Read, this grants access to the dashboard. As a project owner (ex. Rakhshan Division), I couldn't share Zhob Division / Zhob WS it to Nasirabad.
<img width="1680" alt="Quetta (Project Owner) Sharing to Kalat" src="https://user-images.githubusercontent.com/50957748/72773042-d1950800-3c40-11ea-9bbb-ff5dad9aea0f.png">
<img width="1680" alt="Rakshan Sharing (WS Owner) to Nasirabad" src="https://user-images.githubusercontent.com/50957748/72773064-e07bba80-3c40-11ea-8ff6-f43733c68cbe.png">

**Comment by SamMousa** [comment]
- [ ] #280

**Comment by SamuelPetragallo** [comment]
General comment that applies at the different levels (global, project and WS): the "Allow everything" option is a little confusing: it's not clear whether it's all possible permissions, or only the ones that can be shared (although it should logically be 2.). Wondering whether this adds or should be removed all together.

The other issue is that "Allow everything" actually provides additional permissions which are not singled out. If we take the example of WS level, it also provides: 
- data synch 
- WS settings edit 
- WS delete

Synch we had not discussed but if still needed (no longer sure where we are with synch of data) this should come as a bundle with data edit/download permissions 

As for WS settings edit and WS delete these should only be accessible at the Project level. That also means - at the Project level - that we should ideally separate project settings edit from dashboard edit to allow pushing the Project settings edit one level up.

**Comment by SamMousa** [comment]
Allow everything does exactly what it says. It is not the same as checking all other boxes.

The permissions are all singled out during access checking. When sharing some are just not shown because they were not part of shy role.

So to delete a workspace you need to have delete permission. You can be given this permission explicitly, or it can cascade from having manage workspaces on the project.

**Comment by SamMousa** [comment]
Having admin permissions on an object means the answer to *can I do xxxx to this object* is always yes.

**Comment by SamuelPetragallo** [comment]
Here's our feedback (after some brain twisting):

The main issue is the need to distribute (and restrict the management of) certain permissions on a given object at higher up levels.

Example: the create, edit (properties) and delete permissions to an object can only be granted at level+1 by level+2. Meaning permissions to create, edit (properties) and delete WSs for example are assigned at the project level by the global level.

Same goes with create, edit (properties) and delete Projects which are currently assigned by the super admin to global admins.

That implies that the current “Manage workspaces” permission for example should not cascade the create, edit (properties) and delete permissions. Similarly the "Allow everything" should not allow those permissions, and the question remains of the utility/clarity of this option (vs. spelling out individual permissions which will be clearer)

That also provides a solution regarding the “share” permission based on what you suggested back in October: we go for the option of a super_share permission (that will be granted at Project level by Global admins) and that will allow Project level grant “Share” permission at WS level.

I'm exhausted... and off for a nap (hoping that works for you! :p )

**Comment by SamMousa** [comment]
> Meaning permissions to create, edit (properties) and delete WSs for example are assigned at the project level by the global level.

> That implies that the current “Manage workspaces” permission for example should not cascade the create, edit (properties) and delete permissions. 

The above 2 statements contradict each other. Currently manage workspaces is a permission that you assign for a project. It then allows managing the workspaces in that project thus cascading as mentioned in the first statement. But then the 2nd statement says it should not cascade...

>  Similarly the "Allow everything" should not allow those permissions, and the question remains of the utility/clarity of this option (vs. spelling out individual permissions which will be clearer)

Allow everything does exactly what it says currently, whether you want to use that permission is a different point of discussion. There should never ever be a permission called *Allow everything* that does not allow everything.
Note that people only see permissions they are allowed to assign, so if you are not assigning that permission anywhere, no one but global admins will see it.

> That also provides a solution regarding the “share” permission based on what you suggested back in October: we go for the option of a super_share permission (that will be granted at Project level by Global admins) and that will allow Project level grant “Share” permission at WS level.

There are no levels. While some permissions cascade from a project to a workspace they still also apply to the project.
That means that if you assign the super share permission to a project, the user will be able to share the `share` permission for that project and the workspaces it contains.

**Comment by SamuelPetragallo** [comment]
1. Yes wrong example indeed, but the idea still is that create a WS, edit properties of a WS, delete a WS and share permissions on a WS can only be granted at Project level.

2. Agree. Since we won't use it, I suggest we remove the "allow everything" to avoid confusion

3. This is where a lot of the back and forth is happening on this: we actually need levels. Permissions need to be limited depending on the level. That may imply substantial technical complications which we'd then need to understand and discuss further, but from the functional perspective there's no satisfactory workaround.

Note that timewise we've discussed with @JeffDotingco and @luna404 and can go ahead with upcoming trainings (Yemen) and deployment (Burkina) with the current setup on prod. Meaning we can take the time required to address this

**Comment by SamMousa** [comment]
> Agree. Since we won't use it, I suggest we remove the "allow everything" to avoid confusion

This is just for global admins, which is 5 people. If you remove it know I can all but guarantee a situation comes up where you will want it. Why not just instruct the global admins to not grant it for now and when a situation arises where you do want this you can handle it.

> This is where a lot of the back and forth is happening on this: we actually need levels. Permissions need to be limited depending on the level. That may imply substantial technical complications which we'd then need to understand and discuss further, but from the functional perspective there's no satisfactory workaround.

I don't think that's true, I've examined every role and they are all covered. This is why we specified the roles, so that I could check whether a given implementation is powerful enough to express the restrictions you need. The current implementation, with the extra share option, is powerful enough and there is no role defined in the document that cannot be implemented in the system. 
If you have a specific issue (like we had earlier with sharing the share permission) then provide them; blindly implementing vaguely defined *levels* to satisfy some unclear requirement is not the way to go.

**Comment by SamuelPetragallo** [comment]
Functionally there are levels, and these can currently not be implemented as needed unless I've missed an update: create a WS, edit properties of a WS, delete a WS can only be given at Project level.

The roles, functionally speaking, were always only meant to be a pre-defined set of more granular permissions

**Comment by SamMousa** [comment]
> Functionally there are levels, and these can currently not be implemented as needed unless I've missed an update: create a WS, edit properties of a WS, delete a WS can only be given at Project level.

This is abstract; tell me which of the roles you are having issues with and either I can explain how to assign permissions to implement that role, or I conclude that we cannot and there is indeed some functionality missing.

**Comment by SamuelPetragallo** [comment]
If we keep going down that route we risk pushing the abstractness on the side of the end users (even if what we have is theoretically robust), which is really not what we want. 

I feel the detailed description of can and can't at the different levels (because they are actual managerial levels in the process and are by no means abstract in "real life situation") was quite clear from the start.

They were then implemented differently than the structure we designed initially (I was personally expecting to find a replica of the excel spreadsheet in the various "share" menus), which in principle is not problem. But the fact that we have now been struggling so much on this demonstrates I think that there's an issue (I'm assuming here that our combined experience doesn't equal to null ;) ).

Back to the example above: a user with no other permissions at the Project level than Project Read permissions should not be granted create a WS, edit properties of a/that WS, delete a/that WS. And that should be crystal clear when implemented to all users

**Comment by SamuelPetragallo** [comment]
There's obviously some misunderstanding here :D
We will work on describing what we have developed more visually (some chart of some sort), that way we can

1. hopefully get it clearer
2. maybe identify issues in what we had in mind that we are not seeing now

As said, we'll move ahead in Yemen and Burkina with Prod as is. I'm hoping maybe Monday we can take some time and start drawing things down

**Comment by SamMousa** [comment]
> If we keep going down that route we risk pushing the abstractness on the side of the end users (even if what we have is theoretically robust), which is really not what we want.

Not sure what you mean by this

> They were then implemented differently than the structure we designed initially (I was personally expecting to find a replica of the excel spreadsheet in the various "share" menus). 

This is still the goal and something that we can do for most roles already. 
The only current issue with that is that granting someone a role that gives them permission to share would (currently) allow them to give someone else the same role.   
This is why the first iteration of this system will use the individual permissions. It is not the final version and not intended to be the final version.

> But the fact that we have now been struggling so much on this demonstrates I think that there's an issue (I'm assuming here that our combined experience on this should also be considered, even lightly).

We have not been struggling so much. We have:
- Implemented the new system
- Did one iteration of testing
- Fixed obvious bugs
- Identified 1 scenario that was not yet supported (even though it was clearly discussed up front)
- Implemented that scenario via Super Share

Currently we are ready for testing the new scenario that we implemented.

I am confident that the permission system as designed will allow us to do what we need to do and think that any worries stem from a lack of understanding of the system. This is why I have repeatedly asked for specific things that you can not implement. 

Note that understanding the system is not needed, all you need to do is specify the roles as done in the first post of this discussion. Based on that document I have given example configurations that you can use while we do not have the final implementation of selecting roles directly.  

> Back to the example above: a user with no other permissions at the Project level than Project Read permissions should not be granted create a WS, edit properties of a/that WS, delete a/that WS. And that should be crystal clear when implemented to all users

Is this something you have actually tried? Because if granting person A read permission on user X allows them create a workspace that is a bug, I am not aware of such a bug. 
To confirm I created a user named `Project Viewer` and gave him read permission on the Bangladesh project. This user can:
- View the project dashboard
- List the workspaces

![image](https://user-images.githubusercontent.com/547021/72997390-9808fc00-3dfc-11ea-8f07-f5c292595fce.png)

![image](https://user-images.githubusercontent.com/547021/72997426-a5be8180-3dfc-11ea-801f-51104060f780.png)

**Comment by SamMousa** [comment]
> Suggestion: we will work on drawing what we have developed more visually (some chart of some sort)

I have a different suggestion; use the logic approach.

Given the claim *things like X cannot be done*

The process to prove or disprove this claim is simple:
1. You give a specific example of a thing in X and ask me to show how to do it.
2. If I find a solution for doing it we must conclude that the claim is false, if I cannot find a solution then the claim is at least partially true.

We went through this process earlier today with the `Super Share` permission and it is clear and efficient.
