### ISSUE TITLE
Data export as Text still has question codes

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#261]
If you download data as text, ranking question only include the codes but not the answer texts. 

![image](https://user-images.githubusercontent.com/18245059/70523020-6d136300-1b42-11ea-98ff-60334b131ec3.png)

https://herams.org/project/24/workspaces

**Comment by SamMousa** [comment]
Working on new implementation of CSV export, will be on staging today.

**Comment by SamMousa** [comment]
I have rebuilt the export module, it is now more flexible, please give it a shot!

**Comment by luna404** [comment]
The new flexibility is great. There's a few things I noticed.

1. UOID column is empty
2. The record ID field seems to be missing #233 
3. Any chance we can open the discussion on the order of the fields again? Not maintaining the LS field order will cause issues with users in the field. 
4. There is an issue with the exports for Mali. It seems to be exporting all versions of a record. If you look for example at Mali - workspace for Kidal (https://herams-staging.org/workspace/5402/export) it exports 42 records instead of only 13. They don't have permissions to update records so there should only be one response per HF.

**Comment by SamMousa** [comment]
- [ ] Remove `UOID` column from the export
- [ ] Remove `Update` from the export
- [ ] Add UOID to the export under a different name. The platform stores this somewhere else since it is a special field.
- [ ] Add Update to the export under a different name. The platform stores this somewhere else since it is a special field.
- [ ] Add last updated field to the export, this is the date where the platform last synced data from this response.
- [ ] External record ID will be added (this is the id from LS)
- [ ] Direct link will be added (this is a link to the page to view the response in LS)

> Any chance we can open the discussion on the order of the fields again? Not maintaining the LS field order will cause issues with users in the field.

Technically it can be done, but we should be looking into decoupling data analysis from data gathering instead of coupling it more closely.

> There is an issue with the exports for Mali. It seems to be exporting all versions of a record. If you look for example at Mali - workspace for Kidal (https://herams-staging.org/workspace/5402/export) it exports 42 records instead of only 13. They don't have permissions to update records so there should only be one response per HF.

I think this has to do with not syncing removals. The records are I am seeing date all the way back to 2016. Try a manual sync to resolve it for this workspace specifically.

**Comment by SamMousa** [comment]
The export should now sort groups as well as top level questions.

**Comment by SamMousa** [comment]
Please have another look, I have added some more meta-data columns.
The columns that are not coming directly from LS are first in the CSV file, the LS columns come after that but should be ordered correctly now.

We could make (some) of these extra columns optional in the future, they will be helpful mostly for validation / tracking down errors, not for real analysis.
These columns include:
- external_id (The LS response ID)
- external_url (The LS view response page)
- subject_id (The identifier of whatever subject we are reporting on, currently it is Health Facility identified by the UOID)
- last_synced (The last time this individual record was synced with the external source)
- date (The date for which the data applies)

Some of these columns are explicitly checked by the platform upon submission, so even though they are gathered via the survey they are stored and handled separately.
In the future we might move facility management to the platform and away from LS, this is why we store and handle the UOID in a special way.

**Comment by luna404** [comment]
Thanks a lot for the changes, this will make it much easier for users.
 
You were right with the sync issue for Mali. Does this mean we need to continue refreshing all the workspaces manually? I though workspaces on staging refresh automatically when you edit the data.
