### ISSUE TITLE
Role: Project Admin

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#282]
This issue is to test project admin permissions.

- [x] Can download data both at project and WS level
- [x] Can share project to others specifically: read, data, create / delete workspaces, export
- [x] Can share workspaces in the project: read, data, create / delete workspaces, export
- [x] Can unshare project, specifically: read, data, create / delete workspaces, export
- [x] Can unshare workspaces in the project: read, data, create / delete workspaces, export
- [x] Can view project dashboard

**Comment by JeffDotingco** [comment]
| Permissions | Status | Remarks
|--------|----------|----------|  
| Can download data both at project and WS level|working|had to double-check with other projects because HeRAMS Pakistan dataset was empty, working in HeRAMS Comores but dataset should follow LS format / arrangement of variables 
| Can share project to others specifically: read, data, create / delete workspaces, export| working 
| Can share workspaces in the project: read, data, create / delete workspaces, export| working 
| Can unshare project, specifically: read, data, create / delete workspaces, export| working 
| Can unshare workspaces in the project: read, data, create / delete workspaces, export| working 
| Can view project dashboard|working

**Comment by SamMousa** [comment]
The role project admin is not the same as having admin access. As discussed sharing is always explicit

**Comment by SamMousa** [comment]
I just tested this again, it works for me.
I assume you are using the `Project Admin` user I created for testing purposes.

**Comment by luna404** [comment]
It's the same issue with the `Project Admin` user. 

Project Admin
![image](https://user-images.githubusercontent.com/18245059/72969491-db944380-3dc5-11ea-9fa3-63734b8ee8d6.png)


A project admin needs to be able to grant share permission to the Workspace Owner. As mentioned in issue #256 we don't want Workspace Owners to have the permission to edit/delete workspace properties. Therefore we need the option to share the `share permissions`

**Comment by SamMousa** [comment]
That's not possible as decided here: https://github.com/WorldHealthOrganization/herams-backend/issues/245#issuecomment-564097763

**Comment by SamMousa** [comment]
@luna404 I think we now support this use case:
![image](https://user-images.githubusercontent.com/547021/72985458-4d7c8500-3de6-11ea-9a4a-67808ba0dcf1.png)

Note that I have created a user called Project Admin for testing purposes.
You can log in as that user via admin > user > impersonate.

**Comment by luna404** [comment]
We changed the project admin permissions to this

![image](https://user-images.githubusercontent.com/18245059/73749943-a04a2b00-475c-11ea-8883-04039804cbb4.png)

With the above permissions, the project admin could perform all his functions with the exception to granting super share to a workspace owner (see #302).
