### ISSUE TITLE
Worldmap zoom level is arbitrary

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#40]
Map needs to zoom so that all projects are in the frame (right now the display seems to be static and centered on Nigeria)

**Comment by SamMousa** [comment]
Map now autofits to the bounds of all markers.
Some HFs have invalid values for latitude or longitude.
To prevent invalid zoom I'm coercing all these values to the correct range (0 - 90 or 0 - 180).
I do this by dividing by 10 until the value is valid (since large values likely mean a missing decimal separator).
