### ISSUE TITLE
Project popup bug

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#45]
Occasionally, the project popup (NGA) returns the following error message

**Comment by SamMousa** [comment]
I'm aware of the issue, it'll automatically get fixed when he implement cache prefilling.
I had an alternative implementation that kept retrying, but since limesurvey can crash multiple times in a row this made it so that loading could take 60+ seconds.

Now instead you get an error in a reasonable time so we're aware of what to fix.

**Comment by SamMousa** [comment]
Fixed!
