### ISSUE TITLE
Location filter picks district code instead of district name

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#78]
![image](https://user-images.githubusercontent.com/15345099/55177934-ac507e00-5184-11e9-85a7-3148edf8df8c.png)

**Comment by SamMousa** [comment]
So the change in LS to this approach is a bit soon ;-)

**Comment by SamuelPetragallo** [comment]
Not sure what you meant there? :D can you specify please?

**Comment by SamMousa** [comment]
Well we discussed moving to a closed question (single choice instead of open text).
But this change requires changes in HeRAMS to use that closed question for the filter, so you went ahead with updating the survey but did not inform me. So now the survey is ready but HeRAMS has not yet been adapted to support the new structure.

This is not a quick fix, so won't be today.

**Comment by SamMousa** [comment]
Also, we must update all surveys to have the same structure.

**Comment by SamuelPetragallo** [comment]
Yes, not always 200% aware of potential links (I thought of that afterwards obviously). Added to the Wiki as a std variable. Plus, we discussed to have all filters in the same "filter window" - this may change things (though we will still want to apply some particular display to that one)

**Comment by SamMousa** [comment]
If this question is a single choice question everywhere I can start changes to the filter. Let me know when this is the case.

**Comment by SamMousa** [comment]
This is no longe relevant.
